version: '3.4'

name: product_services
services:
  product_api:
    build:
      context: .
      dockerfile: Product.API/Dockerfile
    ports:
      - "5000:8080"
    depends_on:
      - docker_sqlserver

  docker_sqlserver:
    container_name: docker_sqlserver
    build:
      context: .
      dockerfile: Product.API/db.Dockerfile
    ports:
      - "1433:1433"