version: '3.8'

name: product_services
services:
  productapi:
    build:
      context: .
      dockerfile: Product.API/Dockerfile
    ports:
      - "5000:8080"
    depends_on:
      - sqlserver

  sqlserver:
    container_name: sqlserver
    build:
      context: .
      dockerfile: Product.API/Dockerfile.sqlserver
    ports:
      - "1433:1433"
    volumes:
      - sqlserver:/var/lib/mssql/data

volumes:
  sqlserver:
